In [ ]:
from pathlib import Path
import pandas as pd
import tensorflow as tf ## deep learning library which will handle loading image tensors, building nn, training the modelm calculating loss, updating weights and making predicitions
import matplotlib.pyplot as plt

2.21.0

load split csv files

In [3]:
PROJECT_ROOT = Path("..")
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

train_df = pd.read_csv(PROCESSED_DIR / "train.csv")
val_df = pd.read_csv(PROCESSED_DIR / "val.csv")
test_df = pd.read_csv(PROCESSED_DIR / "test.csv")

train_df.head()

,original_path,processed_path,label
0,..\data\raw\inflammatory_acne\inflam_021.jpg,..\data\processed\inflammatory_acne\inflammato...,inflammatory_acne
1,..\data\raw\comedonal_closed\come_048.png,..\data\processed\comedonal_closed\comedonal_c...,comedonal_closed
2,..\data\raw\comedonal_open\comeo_008.png,..\data\processed\comedonal_open\comedonal_ope...,comedonal_open
3,..\data\raw\acne_scars\scar_016.png,..\data\processed\acne_scars\acne_scars_0016.jpg,acne_scars
4,..\data\raw\acne_scars\scar_041.png,..\data\processed\acne_scars\acne_scars_0041.jpg,acne_scars

get class names

In [4]:
class_names = sorted(train_df["label"].unique())
class_names

['acne_excoriee',
 'acne_scars',
 'comedonal_closed',
 'comedonal_open',
 'inflammatory_acne']

create a label mapping
ie: 0 = class 1 label, 1 = class 2, 2 = class 3, etc

need this since ml models work with numbers instead of text process = label encoding

In [5]:
label_to_index = {label: index for index, label in enumerate(class_names)}
label_to_index

{'acne_excoriee': 0,
 'acne_scars': 1,
 'comedonal_closed': 2,
 'comedonal_open': 3,
 'inflammatory_acne': 4}

add the numeric labels to dataframes df

In [6]:
train_df["label_index"] = train_df["label"].map(label_to_index)
val_df["label_index"] = val_df["label"].map(label_to_index)
test_df["label_index"] = test_df["label"].map(label_to_index)

train_df.head()

,original_path,processed_path,label,label_index
0,..\data\raw\inflammatory_acne\inflam_021.jpg,..\data\processed\inflammatory_acne\inflammato...,inflammatory_acne,4
1,..\data\raw\comedonal_closed\come_048.png,..\data\processed\comedonal_closed\comedonal_c...,comedonal_closed,2
2,..\data\raw\comedonal_open\comeo_008.png,..\data\processed\comedonal_open\comedonal_ope...,comedonal_open,3
3,..\data\raw\acne_scars\scar_016.png,..\data\processed\acne_scars\acne_scars_0016.jpg,acne_scars,1
4,..\data\raw\acne_scars\scar_041.png,..\data\processed\acne_scars\acne_scars_0041.jpg,acne_scars,1

ml overview:

in this case the image is the input x and the label is the target y

each row is basically x and y where its image path and numeric class label

separate image paths and labels

In [7]:
train_df["label_index"] = train_df["label"].map(label_to_index)
val_df["label_index"] = val_df["label"].map(label_to_index)
test_df["label_index"] = test_df["label"].map(label_to_index)

train_df.head()

,original_path,processed_path,label,label_index
0,..\data\raw\inflammatory_acne\inflam_021.jpg,..\data\processed\inflammatory_acne\inflammato...,inflammatory_acne,4
1,..\data\raw\comedonal_closed\come_048.png,..\data\processed\comedonal_closed\comedonal_c...,comedonal_closed,2
2,..\data\raw\comedonal_open\comeo_008.png,..\data\processed\comedonal_open\comedonal_ope...,comedonal_open,3
3,..\data\raw\acne_scars\scar_016.png,..\data\processed\acne_scars\acne_scars_0016.jpg,acne_scars,1
4,..\data\raw\acne_scars\scar_041.png,..\data\processed\acne_scars\acne_scars_0041.jpg,acne_scars,1